//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prescriptions.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prescriptions.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Leki&gt;
        ///  &lt;Lek BL7=&quot;8085922&quot; EAN=&quot;5909990002306&quot; psychotrop=&quot;False&quot; senior=&quot;True&quot; szczepionka=&quot;True&quot; cena=&quot;123,45&quot;&gt;
        ///    &lt;Nazwa&gt;Test name&lt;/Nazwa&gt;
        ///    &lt;NazwaInt&gt;Test international name&lt;/NazwaInt&gt;
        ///    &lt;Postać&gt;Test form&lt;/Postać&gt;
        ///    &lt;Dawka&gt;Test dosage&lt;/Dawka&gt;
        ///    &lt;Opakowanie&gt;Test packaging&lt;/Opakowanie&gt;
        ///    &lt;Refundacja&gt;
        ///      &lt;Poziom poziom=&quot;ryczałt&quot;&gt;lump sum&lt;/Poziom&gt;
        ///      &lt;Poziom poziom=&quot;30%&quot;&gt;thirty&lt;/Poziom&gt;
        ///      &lt;Poziom poziom=&quot;50%&quot;&gt;fifty&lt;/Poziom&gt;
        ///      &lt;Pozi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestXml {
            get {
                return ResourceManager.GetString("TestXml", resourceCulture);
            }
        }
    }
}
